/**
 * 
 */
package com.bcgi.paymgr.posserver.domestic.common.constant;

/**
 * @author venugopalp
 *
 */
public class AppMoniterEventConstants {
	public static final String CARRIER_ID = "1000";
	public static final String RECHARGE_GATEWAY_DOMPOS_SUCCESS = "PMLS_GATEWAY-DOMPOS_RECHARGE_RECHARGE_RTT_SUCCESS";
	public static final String RECHARGE_GATEWAY_DOMPOS_REJECTED = "PMLS_GATEWAY-DOMPOS_RECHARGE_RECHARGE_RTT_REJECTED";
	public static final String PIN_RECHARGE_GATEWAY_DOMPOS_SUCCESS = "PMLS_GATEWAY-DOMPOS_PINRECHARGE_PINRECHARGE_RTT_SUCCESS";
	public static final String PIN_RECHARGE_GATEWAY_DOMPOS_REJECTED = "PMLS_GATEWAY-DOMPOS_PINRECHARGE_PINRECHARGE_RTT_REJECTED";
	public static final String REVERSAL_GATEWAY_DOMPOS_SUCCESS = "PMLS_GATEWAY-DOMPOS_REVERSAL_REVERSAL_RTT_SUCCESS";
	public static final String REVERSAL_GATEWAY_DOMPOS_REJECTED = "PMLS_GATEWAY-DOMPOS_REVERSAL_REVERSAL_RTT_REJECTED";
	public static final String PIN_REVERSAL_GATEWAY_DOMPOS_SUCCESS = "PMLS_GATEWAY-DOMPOS_PINREVERSAL_PINREVERSAL_RTT_SUCCESS";
	public static final String PIN_REVERSAL_GATEWAY_DOMPOS_REJECTED = "PMLS_GATEWAY-DOMPOS_PInREVERSAL_PINREVERSAL_RTT_REJECTED";
	public static final String ECHO_GATEWAY_DOMPOS_SUCCESS = "PMLS_GATEWAY-DOMPOS_ECHO_ECHO_RTT_SUCCESS";
	public static final String ECHO_GATEWAY_DOMPOS_REJECTED = "PMLS_GATEWAY-DOMPOS_ECHO_ECHO_RTT_REJECTED";
	  
	public static final String RECHARGE_INQUIRY_GATEWAY_DOMPOS_SUCCESS = "PMLS_GATEWAY-DOMPOS_RECHARGEINQUIRY_RECHARGEINQUIRY_RTT_SUCCESS";
	public static final String RECHARGE_INQUIRY_GATEWAY_DOMPOS_REJECTED = "PMLS_GATEWAY-DOMPOS_RECHARGEINQUIRY_RECHARGEINQUIRY_RTT_REJECTED";
	
	public static final String RECHARGE_GATEWAY_DOMPOS_SEG_SUCCESS = "PMLS_GATEWAY-DOMPOS_RECHARGE_RECHARGE_SEG_SUCCESS";
	public static final String RECHARGE_GATEWAY_DOMPOS_SEG_REJECTED = "PMLS_GATEWAY-DOMPOS_RECHARGE_RECHARGE_SEG_REJECTED";
	public static final String REVERSAL_GATEWAY_DOMPOS_SEG_SUCCESS = "PMLS_GATEWAY-DOMPOS_REVERSAL_REVERSAL_SEG_SUCCESS";
	public static final String REVERSAL_GATEWAY_DOMPOS_SEG_REJECTED = "PMLS_GATEWAY-DOMPOS_REVERSAL_REVERSAL_SEG_REJECTED";
	public static final String ECHO_GATEWAY_DOMPOS_SEG_SUCCESS = "PMLS_GATEWAY-DOMPOS_ECHO_ECHO_SEG_SUCCESS";
	public static final String ECHO_GATEWAY_DOMPOS_SEG_REJECTED = "PMLS_GATEWAY-DOMPOS_ECHO_ECHO_SEG_REJECTED";
	public static final String RECHARGE_ENQ_GATEWAY_DOMPOS_SEG_SUCCESS = "PMLS_GATEWAY-DOMPOS_RECHARGE_ENQ_SEG_SUCCESS";
	public static final String RECHARGE_ENQ_GATEWAY_DOMPOS_SEG_REJECTED = "PMLS_GATEWAY-DOMPOS_RECHARGE_ENQ_SEG_REJECTED";
	public static final String SUB_VALIDATION_GATEWAY_DOMPOS_SEG_SUCCESS = "PMLS_GATEWAY-DOMPOS_SUB_VALIDATION_SEG_SUCCESS";
	public static final String SUB_VALIDATION_GATEWAY_DOMPOS_SEG_REJECTED = "PMLS_GATEWAY-DOMPOS_SUB_VALIDATION_SEG_REJECTED";
	
	public static final String ASYNC_RECHARGE_GATEWAY_DOMPOS_SEG_SUCCESS = "PMLS_GATEWAY-DOMPOS_ASYNC_RECHARGE_SEG_SUCCESS";
	public static final String ASYNC_RECHARGE_GATEWAY_DOMPOS_SEG_REJECTED = "PMLS_GATEWAY-DOMPOS_ASYNC_RECHARGE_SEG_REJECTED";
	public static final String UNIFIED_RECHARGE_GATEWAY_DOMPOS_SEG_SUCCESS = "PMLS_GATEWAY-DOMPOS_UNIFIED_RECHARGE_SEG_SUCCESS";
	public static final String UNIFIED_RECHARGE_GATEWAY_DOMPOS_SEG_REJECTED = "PMLS_GATEWAY-DOMPOS_UNIFIED_RECHARGE_SEG_REJECTED";
	public static final String ASYNC_REVERSAL_GATEWAY_DOMPOS_SEG_SUCCESS = "PMLS_GATEWAY-DOMPOS_ASYNC_REVERSAL_SEG_SUCCESS";
	public static final String ASYNC_REVERSAL_GATEWAY_DOMPOS_SEG_REJECTED = "PMLS_GATEWAY-DOMPOS_ASYNC_REVERSAL_SEG_REJECTED";

	public static final String ASYNCRECHARGE_GATEWAY_DOMPOS_SUCCESS = "PMLS_GATEWAY-DOMPOS_ASYNCRECHARGE_ASYNCRECHARGE_RTT_SUCCESS";
	public static final String ASYNCRECHARGE_GATEWAY_DOMPOS_REJECTED = "PMLS_GATEWAY-DOMPOS_ASYNCRECHARGE_ASYNCRECHARGE_RTT_REJECTED";
	
	
	public static final String ASYNCREVERSAL_GATEWAY_DOMPOS_SUCCESS = "PMLS_GATEWAY-DOMPOS_ASYNCREVERSAL_ASYNCREVERSAL_RTT_SUCCESS";
	public static final String ASYNCREVERSAL_GATEWAY_DOMPOS_REJECTED = "PMLS_GATEWAY-DOMPOS_ASYNCREVERSAL_ASYNCREVERSAL_RTT_REJECTED";
	
	
	public static final String UNIASYNCRECHARGE_GATEWAY_DOMPOS_SUCCESS = "PMLS_GATEWAY-DOMPOS_UNIASYNCRECHARGE_UNIASYNCRECHARGE_RTT_SUCCESS";
	public static final String UNIASYNCRECHARGE_GATEWAY_DOMPOS_REJECTED = "PMLS_GATEWAY-DOMPOS_UNIASYNCRECHARGE_UNIASYNCRECHARGE_RTT_REJECTED";



	
	public static final String COUPON_RECHARGE_GATEWAY_DOMPOS_SUCCESS = "PMLS_GATEWAY-DOMPOS_RECHARGE_COUPON_REDEEMPTION_RTT_SUCCESS";
	public static final String COUPON_RECHARGE_GATEWAY_DOMPOS_REJECTED = "PMLS_GATEWAY-DOMPOS_RECHARGE_COUPON_REDEEMPTION_RTT_REJECTED";
	
	
	public static final String BRAND_CPN_REDEEMPTION_GATEWAY_DOMPOS_SUCCESS = "PMLS_GATEWAY-DOMPOS_BRAND_COUPON_REDEEMPTION_RTT_SUCCESS";
	public static final String BRAND_CPN_REDEEMPTION_GATEWAY_DOMPOS_REJECTED ="PMLS_GATEWAY-DOMPOS_BRAND_COUPON_REDEEMPTION_RTT_REJECTED";

}
